services:
  app:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: laravel-api:latest
    container_name: app_challenge
    volumes:
      - .:/var/www
    networks:
      - app_challenge_network
    ports:
      - "8085:8085"
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: app_challenge_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: project
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
      MYSQL_ROOT_HOST: '%'
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_challenge_network

networks:
  app_challenge_network:
    driver: bridge

volumes:
  mysql_data: